In [1]:
print("Ejecicio 1")

Ejecicio 1


In [2]:
print("Hola mundo")

Hola mundo


# NumPy

In [ ]:
pip install numpy

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.array([1,2,3,4,5,6], ndmin=-3)
print(arr.ndim)

In [7]:
arr=np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [10]:
arr= [1,2,3]
arr2= [4,5,6]
arr3= np.add(arr,arr2)
print(arr3)

[5 7 9]


In [11]:
arr= [1,2,3]
arr2= [4,5,6]
arr3= np.subtract(arr,arr2)
print(arr3)

[-3 -3 -3]


In [12]:
arr= [1,2,3]
arr2= [4,5,6]
arr3= np.multiply(arr,arr2)
print(arr3)

[ 4 10 18]


Agregacion

In [13]:
arr=[1,5,7]
media=np.median(arr)
print(media)

2.0


In [20]:
arr=[1,5,7]
media=np.mean(arr)
print(media)

4.333333333333333


In [19]:
arr=[1,5,7]
maximo = np.max(arr)
print(maximo)

7


indexacion

In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [24]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])

6


In [ ]:
arr = np.array([1,2,3],[4,5,6])
print(arr[1,2])

In [26]:
arr = np.array([1,2,2,4,5,6])
print(arr[1:4])

[2 2 4]


In [27]:
arr = np.array([1,2,2,4,5,6])
print(arr[1:4:2])

[2 4]
