In [1]:
print("Ejecicio 1")

Ejecicio 1


In [2]:
print("Hola mundo")

Hola mundo


# NumPy

In [ ]:
pip install numpy

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.array([1,2,3,4,5,6], ndmin=-3)
print(arr.ndim)

In [7]:
arr=np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [10]:
arr= [1,2,3]
arr2= [4,5,6]
arr3= np.add(arr,arr2)
print(arr3)

[5 7 9]


In [11]:
arr= [1,2,3]
arr2= [4,5,6]
arr3= np.subtract(arr,arr2)
print(arr3)

[-3 -3 -3]


In [12]:
arr= [1,2,3]
arr2= [4,5,6]
arr3= np.multiply(arr,arr2)
print(arr3)

[ 4 10 18]


Agregacion

In [13]:
arr=[1,5,7]
media=np.median(arr)
print(media)

2.0


In [20]:
arr=[1,5,7]
media=np.mean(arr)
print(media)

4.333333333333333


In [19]:
arr=[1,5,7]
maximo = np.max(arr)
print(maximo)

7


indexacion

In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [24]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])

6


In [ ]:
arr = np.array([1,2,3],[4,5,6])
print(arr[1,2])

In [26]:
arr = np.array([1,2,2,4,5,6])
print(arr[1:4])

[2 2 4]


In [27]:
arr = np.array([1,2,2,4,5,6])
print(arr[1:4:2])

[2 4]


Tipos de datos

In [1]:
arr= np.array([1.1,2.1,3.1])

print("pre",arr)

nuevo_arr = arr.astype("1")

print(nuevo_arr)

NameError: name 'np' is not defined

Copy y view

In [12]:
arr=np.array([1,2,2,4,5,5,4])

x=np.where(arr == 5)
print(x) 

NameError: name 'np' is not defined

In [ ]:
arr=np.array([2,5,6,4,1,3])


In [13]:
# PANDAS

pip install pandas

In [14]:
pip install pandas


     --------------------------------------- 10.6/10.6 MB 21.8 MB/s eta 0:00:00
     ------------------------------------- 502.3/502.3 kB 32.8 MB/s eta 0:00:00
     ---------------------------------------- 341.8/341.8 kB ? eta 0:00:00



[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
import pandas as pd

In [17]:
import numpy as np

In [18]:
a = np.array([1,2,3])

srs= pd.Series(a)

print(srs)

0    1
1    2
2    3
dtype: int32


In [23]:
nydataset = [   
    "operador": ["Jhon doe", "sr x","Loren"],
    "no, Reloj": [101, 202, 303]
]

df= pd.DataFrame(nydataset)
print(df)

SyntaxError: invalid syntax (101236593.py, line 2)